package entitiy;
// Generated May 16, 2019 8:48:15 AM by Hibernate Tools 4.3.1



/**
 * Divisi generated by hbm2java
 */
public class Divisi  implements java.io.Serializable {


     private Integer id;
     private String namadivisi;
     private String deskripsi;

    public Divisi() {
    }

    public Divisi(String namadivisi, String deskripsi) {
       this.namadivisi = namadivisi;
       this.deskripsi = deskripsi;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNamadivisi() {
        return this.namadivisi;
    }
    
    public void setNamadivisi(String namadivisi) {
        this.namadivisi = namadivisi;
    }
    public String getDeskripsi() {
        return this.deskripsi;
    }
    
    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }




}


