package entitiy;
// Generated May 16, 2019 8:48:15 AM by Hibernate Tools 4.3.1



/**
 * Formpendaftaran generated by hbm2java
 */
public class Formpendaftaran  implements java.io.Serializable {


     private Integer id;
     private String namalengkap;
     private String email;
     private String umur;
     private String tgllahir;
     private String alamat;
     private String notlp;
     private String jeniskelamin;
     private String pendidikan;
     private String pengalamanbekerja;
     private String posisi;
     private String motivasi;
     private String cv;

    public Formpendaftaran() {
    }

    public Formpendaftaran(String namalengkap, String email, String umur, String tgllahir, String alamat, String notlp, String jeniskelamin, String pendidikan, String pengalamanbekerja, String posisi, String motivasi, String cv) {
       this.namalengkap = namalengkap;
       this.email = email;
       this.umur = umur;
       this.tgllahir = tgllahir;
       this.alamat = alamat;
       this.notlp = notlp;
       this.jeniskelamin = jeniskelamin;
       this.pendidikan = pendidikan;
       this.pengalamanbekerja = pengalamanbekerja;
       this.posisi = posisi;
       this.motivasi = motivasi;
       this.cv = cv;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNamalengkap() {
        return this.namalengkap;
    }
    
    public void setNamalengkap(String namalengkap) {
        this.namalengkap = namalengkap;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getUmur() {
        return this.umur;
    }
    
    public void setUmur(String umur) {
        this.umur = umur;
    }
    public String getTgllahir() {
        return this.tgllahir;
    }
    
    public void setTgllahir(String tgllahir) {
        this.tgllahir = tgllahir;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getNotlp() {
        return this.notlp;
    }
    
    public void setNotlp(String notlp) {
        this.notlp = notlp;
    }
    public String getJeniskelamin() {
        return this.jeniskelamin;
    }
    
    public void setJeniskelamin(String jeniskelamin) {
        this.jeniskelamin = jeniskelamin;
    }
    public String getPendidikan() {
        return this.pendidikan;
    }
    
    public void setPendidikan(String pendidikan) {
        this.pendidikan = pendidikan;
    }
    public String getPengalamanbekerja() {
        return this.pengalamanbekerja;
    }
    
    public void setPengalamanbekerja(String pengalamanbekerja) {
        this.pengalamanbekerja = pengalamanbekerja;
    }
    public String getPosisi() {
        return this.posisi;
    }
    
    public void setPosisi(String posisi) {
        this.posisi = posisi;
    }
    public String getMotivasi() {
        return this.motivasi;
    }
    
    public void setMotivasi(String motivasi) {
        this.motivasi = motivasi;
    }
    public String getCv() {
        return this.cv;
    }
    
    public void setCv(String cv) {
        this.cv = cv;
    }




}


