package entitiy;
// Generated May 16, 2019 8:48:15 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pengumuman generated by hbm2java
 */
public class Pengumuman  implements java.io.Serializable {


     private Integer id;
     private String judul;
     private String deskripsi;
     private Date tglbuat;

    public Pengumuman() {
    }

    public Pengumuman(String judul, String deskripsi, Date tglbuat) {
       this.judul = judul;
       this.deskripsi = deskripsi;
       this.tglbuat = tglbuat;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getDeskripsi() {
        return this.deskripsi;
    }
    
    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }
    public Date getTglbuat() {
        return this.tglbuat;
    }
    
    public void setTglbuat(Date tglbuat) {
        this.tglbuat = tglbuat;
    }




}


