package entitiy;
// Generated May 16, 2019 8:48:15 AM by Hibernate Tools 4.3.1



/**
 * Program generated by hbm2java
 */
public class Program  implements java.io.Serializable {


     private Integer id;
     private String namaprogram;
     private String penyiar;
     private String deskripsi;
     private String jadwal;

    public Program() {
    }

    public Program(String namaprogram, String penyiar, String deskripsi, String jadwal) {
       this.namaprogram = namaprogram;
       this.penyiar = penyiar;
       this.deskripsi = deskripsi;
       this.jadwal = jadwal;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNamaprogram() {
        return this.namaprogram;
    }
    
    public void setNamaprogram(String namaprogram) {
        this.namaprogram = namaprogram;
    }
    public String getPenyiar() {
        return this.penyiar;
    }
    
    public void setPenyiar(String penyiar) {
        this.penyiar = penyiar;
    }
    public String getDeskripsi() {
        return this.deskripsi;
    }
    
    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }
    public String getJadwal() {
        return this.jadwal;
    }
    
    public void setJadwal(String jadwal) {
        this.jadwal = jadwal;
    }




}


