package entitiy;
// Generated May 16, 2019 8:48:15 AM by Hibernate Tools 4.3.1



/**
 * Syarat generated by hbm2java
 */
public class Syarat  implements java.io.Serializable {


     private Integer id;
     private String nama;
     private String deskripsi;

    public Syarat() {
    }

    public Syarat(String nama, String deskripsi) {
       this.nama = nama;
       this.deskripsi = deskripsi;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getDeskripsi() {
        return this.deskripsi;
    }
    
    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }




}


